# Generated by Django 2.0.3 on 2018-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorLootItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='n', max_length=1)),
                ('item_condition', models.CharField(choices=[('nan', 'na'), ('sha', 'sharp'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('cra', 'cracked'), ('bro', 'broken')], default='na', max_length=3)),
                ('item_material', models.CharField(choices=[('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='woo', max_length=3)),
                ('item_level', models.IntegerField(default=1)),
                ('item_dropped', models.BooleanField(default=False)),
                ('armor_name', models.CharField(choices=[('arm', 'armor'), ('boo', 'boots'), ('shi', 'shield')], default='arm', max_length=3)),
                ('modificator_positive', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('modificator_negative', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=2)),
                ('bonus_to', models.CharField(choices=[('ar', 'armor')], default='ar', max_length=2)),
                ('penalty_to', models.CharField(choices=[('sp', 'speed')], default='sp', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField(default=4)),
                ('armor', models.IntegerField(default=5)),
                ('attack', models.CharField(default='3d6', max_length=3)),
                ('attack_range', models.IntegerField(default=0)),
                ('attack_modifier', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=5)),
                ('character_level', models.IntegerField(default=1)),
                ('character_description', models.TextField(default='Character description...', max_length=1500)),
                ('gamer', models.BooleanField(default=True)),
                ('character_race', models.CharField(choices=[('hum', 'Human'), ('dwa', 'Dwarf'), ('elf', 'Elf')], default='hum', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonsterCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField(default=4)),
                ('armor', models.IntegerField(default=5)),
                ('attack', models.CharField(default='3d6', max_length=3)),
                ('attack_range', models.IntegerField(default=0)),
                ('attack_modifier', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=5)),
                ('character_level', models.IntegerField(default=1)),
                ('character_description', models.TextField(default='Character description...', max_length=1500)),
                ('monster', models.BooleanField(default=True)),
                ('character_race', models.CharField(choices=[('bar', 'Barrel'), ('spd', 'Spider'), ('ske', 'Skeleton'), ('ska', 'Archer Skeleton'), ('fsp', 'Flying Spinner')], default='ske', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrinketLootItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='n', max_length=1)),
                ('item_condition', models.CharField(choices=[('nan', 'na'), ('sha', 'sharp'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('cra', 'cracked'), ('bro', 'broken')], default='na', max_length=3)),
                ('item_material', models.CharField(choices=[('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='woo', max_length=3)),
                ('item_level', models.IntegerField(default=1)),
                ('item_dropped', models.BooleanField(default=False)),
                ('trinket_name', models.CharField(choices=[('amu', 'amulet'), ('rin', 'ring')], default='amu', max_length=3)),
                ('modificator_positive', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1)),
                ('bonus_to', models.CharField(choices=[('at', 'attack'), ('hp', 'health'), ('sp', 'speed'), ('ra', 'range'), ('ar', 'armor')], default='ar', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponLootItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='n', max_length=1)),
                ('item_condition', models.CharField(choices=[('nan', 'na'), ('sha', 'sharp'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('cra', 'cracked'), ('bro', 'broken')], default='na', max_length=3)),
                ('item_material', models.CharField(choices=[('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='woo', max_length=3)),
                ('item_level', models.IntegerField(default=1)),
                ('item_dropped', models.BooleanField(default=False)),
                ('weapon_name', models.CharField(choices=[('bow', 'bow'), ('swo', 'sword'), ('clu', 'club'), ('sti', 'stick'), ('axe', 'axe'), ('ham', 'hammer'), ('arb', 'arbalet')], default='sti', max_length=3)),
                ('modificator', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=3)),
                ('bonus_to', models.CharField(choices=[('at', 'attack'), ('ra', 'range')], default='at', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
