# Generated by Django 2.0.3 on 2018-03-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('attack', models.CharField(default='3d6', max_length=3)),
                ('attack_range', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GamerCaracter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LootItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='na', max_length=1)),
                ('item_condition', models.CharField(choices=[('nan', 'na'), ('dul', 'dull'), ('sha', 'sharp'), ('cra', 'cracked'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('bro', 'broken')], default='na', max_length=3)),
                ('item_material', models.CharField(choices=[('nan', 'na'), ('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='na', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('weapon_name', models.CharField(choices=[('bow', 'bow'), ('swo', 'sword'), ('clu', 'club'), ('sti', 'stick'), ('axe', 'axe'), ('ham', 'hammer'), ('arb', 'arbalet')], default='na', max_length=3)),
            ],
            bases=('main.lootitem',),
        ),
    ]
