# Generated by Django 2.0.3 on 2018-03-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('attack', models.CharField(default='3d6', max_length=3)),
                ('attack_range', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LootItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='n', max_length=1)),
                ('item_condition', models.CharField(choices=[('nan', 'na'), ('sha', 'sharp'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('cra', 'cracked'), ('bro', 'broken')], default='na', max_length=3)),
                ('item_material', models.CharField(choices=[('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='woo', max_length=3)),
                ('item_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('armor_name', models.CharField(choices=[('arm', 'armor'), ('boo', 'boots'), ('shi', 'shield')], default='arm', max_length=3)),
                ('modificator_positive', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('modificator_negative', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='-1', max_length=2)),
                ('bonus_to', models.CharField(choices=[('ar', 'armor')], default='ar', max_length=2)),
                ('penalty_to', models.CharField(choices=[('sp', 'speed')], default='sp', max_length=2)),
            ],
            bases=('main.lootitem',),
        ),
        migrations.CreateModel(
            name='GamerCharacter',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Character')),
                ('gamer', models.BooleanField()),
                ('gamer_description', models.TextField(default='Gamer character description...', max_length=1500)),
                ('gamer_race', models.CharField(choices=[('hum', 'human'), ('dwa', 'dwarf'), ('elf', 'elf')], default='hum', max_length=3)),
            ],
            bases=('main.character',),
        ),
        migrations.CreateModel(
            name='TrinketLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('trinket_name', models.CharField(choices=[('amu', 'amulet'), ('rin', 'ring')], default='amu', max_length=3)),
                ('modificator_positive', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1)),
                ('bonus_to', models.CharField(choices=[('at', 'attack'), ('hp', 'health'), ('sp', 'speed'), ('ra', 'range'), ('ar', 'armor')], default='ar', max_length=2)),
            ],
            bases=('main.lootitem',),
        ),
        migrations.CreateModel(
            name='WeaponLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('weapon_name', models.CharField(choices=[('bow', 'bow'), ('swo', 'sword'), ('clu', 'club'), ('sti', 'stick'), ('axe', 'axe'), ('ham', 'hammer'), ('arb', 'arbalet')], default='sti', max_length=3)),
                ('modificator', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=3)),
                ('bonus_to', models.CharField(choices=[('at', 'attack')], default='at', max_length=2)),
            ],
            bases=('main.lootitem',),
        ),
    ]
