# Generated by Django 2.0.3 on 2018-03-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootitem',
            name='item_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamercharacter',
            name='gamer',
            field=models.BooleanField(default=True),
        ),
    ]
