# Generated by Django 2.0.3 on 2018-03-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponlootitem',
            name='modificator',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default='na', max_length=3),
        ),
    ]
