# Generated by Django 2.0.3 on 2018-03-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamercharacter',
            name='attack',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='monstercharacter',
            name='attack',
            field=models.IntegerField(default=3),
        ),
    ]
