# Generated by Django 2.0.3 on 2018-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180318_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponlootitem',
            name='bonus_to',
            field=models.CharField(choices=[('at', 'attack'), ('ra', 'range')], default='at', max_length=2),
        ),
    ]
