# Generated by Django 2.0.3 on 2018-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180322_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='player_id',
            field=models.CharField(choices=[('vin', 'Duke Vincent'), ('dad', 'Dadrin'), ('idr', 'Idrill')], default='vin', max_length=3),
        ),
    ]
