# Generated by Django 2.0.3 on 2018-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180317_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponlootitem',
            name='modificator',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='na', max_length=3),
        ),
    ]
