# Generated by Django 2.0.3 on 2018-03-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playercharacter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='knocked_down',
            field=models.BooleanField(default=False),
        ),
    ]
