# Generated by Django 2.0.3 on 2018-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180317_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootitem',
            name='item_condition',
            field=models.CharField(choices=[('nan', 'na'), ('sha', 'sharp'), ('goo', 'good'), ('nor', 'normal'), ('poo', 'poor'), ('cra', 'cracked'), ('bro', 'broken')], default='na', max_length=3),
        ),
        migrations.AlterField(
            model_name='lootitem',
            name='item_material',
            field=models.CharField(choices=[('sil', 'silver'), ('gol', 'golden'), ('ste', 'steel'), ('lea', 'leather'), ('woo', 'wooden'), ('rub', 'ruby'), ('opa', 'opal'), ('zir', 'zirkon')], default='woo', max_length=3),
        ),
        migrations.AlterField(
            model_name='lootitem',
            name='item_size',
            field=models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponlootitem',
            name='modificator',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='na', max_length=3),
        ),
    ]
