# Generated by Django 2.0.3 on 2018-03-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180317_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('weapon_name', models.CharField(choices=[('arm', 'armor'), ('boo', 'boots')], default='arm', max_length=3)),
                ('modificator', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=3)),
            ],
            bases=('main.lootitem',),
        ),
        migrations.AlterField(
            model_name='lootitem',
            name='item_size',
            field=models.CharField(choices=[('n', 'na'), ('s', 'small'), ('m', 'medium'), ('l', 'large')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponlootitem',
            name='modificator',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='weaponlootitem',
            name='weapon_name',
            field=models.CharField(choices=[('bow', 'bow'), ('swo', 'sword'), ('clu', 'club'), ('sti', 'stick'), ('axe', 'axe'), ('ham', 'hammer'), ('arb', 'arbalet')], default='sti', max_length=3),
        ),
    ]
