# Generated by Django 2.0.3 on 2018-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180317_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armorlootitem',
            old_name='weapon_name',
            new_name='armor_name',
        ),
        migrations.RemoveField(
            model_name='armorlootitem',
            name='modificator',
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='modificator_negative',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='modificator_positive',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=3),
        ),
    ]
