# Generated by Django 2.0.3 on 2018-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_log', models.TextField(default='Game log start')),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
