# Generated by Django 2.0.3 on 2018-03-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180317_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorlootitem',
            name='modificator_negative',
            field=models.CharField(choices=[('-1', '-1'), ('-2', '-2'), ('-3', '-3'), ('-4', '-4')], default='1', max_length=3),
        ),
    ]
