# Generated by Django 2.0.3 on 2018-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180325_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armorlootitem',
            name='equiped_on',
        ),
        migrations.RemoveField(
            model_name='trinketlootitem',
            name='equiped_on',
        ),
        migrations.RemoveField(
            model_name='weaponlootitem',
            name='equiped_on',
        ),
    ]
