# Generated by Django 2.0.3 on 2018-03-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180325_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponlootitem',
            name='wpn_equipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpn_equipped_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='wpn_found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpn_found_by', to='main.PlayerCharacter'),
        ),
    ]
