# Generated by Django 2.0.3 on 2018-03-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180325_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorlootitem',
            name='arm_equipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arm_equipped_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='arm_found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arm_found_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='trinket_equipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_equipped_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='trinket_found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_found_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='wpn_equipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpn_equipped_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='wpn_found_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpn_found_by', to='main.PlayerCharacter'),
        ),
    ]
