# Generated by Django 2.0.3 on 2018-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180318_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrinketLootItem',
            fields=[
                ('lootitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.LootItem')),
                ('armor_name', models.CharField(choices=[('amu', 'amulet'), ('rin', 'ring')], default='arm', max_length=3)),
                ('modificator_positive', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('modificator_negative', models.CharField(choices=[('na', 'na'), ('1', '1'), ('2', '2'), ('3', '3')], default='-1', max_length=2)),
            ],
            bases=('main.lootitem',),
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='bonus_to',
            field=models.CharField(choices=[('ar', 'armor')], default='ar', max_length=2),
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='penalty_to',
            field=models.CharField(choices=[('sp', 'speed')], default='sp', max_length=2),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='bonus_to',
            field=models.CharField(choices=[('at', 'attack')], default='at', max_length=2),
        ),
        migrations.AlterField(
            model_name='armorlootitem',
            name='armor_name',
            field=models.CharField(choices=[('arm', 'armor'), ('boo', 'boots'), ('shi', 'shield')], default='arm', max_length=3),
        ),
    ]
