# Generated by Django 2.0.3 on 2018-04-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180325_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armorlootitem',
            name='arm_equipped_by',
        ),
        migrations.RemoveField(
            model_name='trinketlootitem',
            name='trinket_equipped_by',
        ),
        migrations.RemoveField(
            model_name='weaponlootitem',
            name='wpn_equipped_by',
        ),
        migrations.AddField(
            model_name='armorlootitem',
            name='arm_owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arm_owned_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='trinket_owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trinket_owned_by', to='main.PlayerCharacter'),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='wpn_owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpn_owned_by', to='main.PlayerCharacter'),
        ),
    ]
