# Generated by Django 2.0.3 on 2018-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180318_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trinketlootitem',
            name='armor_name',
        ),
        migrations.RemoveField(
            model_name='trinketlootitem',
            name='modificator_negative',
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='trinket_name',
            field=models.CharField(choices=[('amu', 'amulet'), ('rin', 'ring')], default='amu', max_length=3),
        ),
        migrations.AlterField(
            model_name='trinketlootitem',
            name='modificator_positive',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1),
        ),
    ]
