# Generated by Django 2.0.3 on 2018-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180416_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorlootitem',
            name='item_equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='item_equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='item_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
