# Generated by Django 2.0.3 on 2018-03-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180318_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trinketlootitem',
            name='bonus_to',
            field=models.CharField(choices=[('at', 'attack'), ('hp', 'health'), ('sp', 'speed'), ('ra', 'range'), ('ar', 'armor')], default='ar', max_length=2),
        ),
    ]
