# Generated by Django 2.0.3 on 2018-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180416_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorlootitem',
            name='item_type',
            field=models.CharField(choices=[('wpn', 'weapon'), ('arm', 'armor'), ('trn', 'trinket')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='trinketlootitem',
            name='item_type',
            field=models.CharField(choices=[('wpn', 'weapon'), ('arm', 'armor'), ('trn', 'trinket')], default='na', max_length=3),
        ),
        migrations.AddField(
            model_name='weaponlootitem',
            name='item_type',
            field=models.CharField(default='wpn', max_length=3),
        ),
    ]
