# Generated by Django 2.0.3 on 2018-04-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180417_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponlootitem',
            name='item_type',
            field=models.CharField(choices=[('wpn', 'weapon'), ('arm', 'armor'), ('trn', 'trinket')], default='na', max_length=3),
        ),
    ]
