# Generated by Django 2.0.3 on 2018-04-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180417_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trinketlootitem',
            old_name='trinket_found_by',
            new_name='trn_found_by',
        ),
        migrations.RenameField(
            model_name='trinketlootitem',
            old_name='trinket_owned_by',
            new_name='trn_owned_by',
        ),
    ]
