# Generated by Django 2.0.3 on 2018-04-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180417_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armorlootitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='trinketlootitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='weaponlootitem',
            name='item_type',
        ),
    ]
