# Generated by Django 2.0.3 on 2018-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180417_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='initial_armor',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='initial_attack_modifier',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='initial_attack_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='initial_health',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='initial_speed',
            field=models.IntegerField(default=5),
        ),
    ]
