# Generated by Django 2.0.3 on 2018-04-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180429_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponlootitem',
            old_name='modificator',
            new_name='modificator_positive',
        ),
    ]
