# Generated by Django 2.0.3 on 2018-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20180429_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='health_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trinketlootitem',
            name='modificator_positive',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=1),
        ),
    ]
