# Generated by Django 2.0.3 on 2018-06-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20180602_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharacter',
            name='health_bonus',
        ),
    ]
